In [7]:
import json
import pandas as pd

def load_json(path):
    rows = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue

            row = {"uniprot_id": obj["uniprot_id"]}
            row.update(obj["GO_terms"].get("0", {}))
            rows.append(row)

    return pd.DataFrame(rows)

df_toxic = load_json("./go_terms_toxic.json")
df_non_toxic = load_json("./go_terms_not_toxic.json")

In [8]:
df_non_toxic.head()

,uniprot_id,GO:0000006,GO:0000007,GO:0000009,GO:0000010,GO:0000014,GO:0000016,GO:0000026,GO:0000030,GO:0000031,...,GO:1990955,GO:1990984,GO:2001065,GO:2001066,GO:2001069,GO:2001070,GO:2001071,GO:2001080,GO:2001147,GO:2001227
0,P84576,0.001279,0.000789,0.000781,0.002387,0.001548,0.000980,0.000861,0.007813,0.001540,...,0.002112,0.000839,0.000739,0.001113,0.000506,0.002859,0.002615,0.000528,0.001097,0.001261
1,A0RJF5,0.000505,0.000371,0.000246,0.001009,0.000760,0.000505,0.000343,0.003700,0.000692,...,0.001437,0.000342,0.000410,0.000468,0.000197,0.000972,0.001316,0.000212,0.000534,0.000614
2,Q3J7R6,0.001667,0.001050,0.000880,0.002838,0.002088,0.001260,0.001108,0.008480,0.002061,...,0.002667,0.001135,0.000977,0.001459,0.000623,0.003301,0.003153,0.000684,0.001355,0.001519
3,P76118,0.000945,0.000598,0.000602,0.002016,0.001485,0.000855,0.000704,0.006246,0.001229,...,0.002063,0.000695,0.000616,0.000897,0.000377,0.002254,0.002248,0.000414,0.000853,0.000972
4,O64725,0.000897,0.000596,0.000469,0.001651,0.001208,0.000733,0.000578,0.005590,0.001124,...,0.001853,0.000561,0.000602,0.000813,0.000346,0.001841,0.002046,0.000368,0.000808,0.000921

In [9]:
df_toxic.head()

,uniprot_id,GO:0000006,GO:0000007,GO:0000009,GO:0000010,GO:0000014,GO:0000016,GO:0000026,GO:0000030,GO:0000031,...,GO:1990955,GO:1990984,GO:2001065,GO:2001066,GO:2001069,GO:2001070,GO:2001071,GO:2001080,GO:2001147,GO:2001227
0,A0S864,0.000142,0.000112,0.000080,0.000394,0.000288,0.000210,0.000085,0.001644,0.000226,...,0.000607,0.000102,0.000161,0.000179,0.000067,0.000372,0.000600,0.000074,0.000187,0.000229
1,A0S865,0.000138,0.000113,0.000073,0.000384,0.000304,0.000212,0.000085,0.001549,0.000217,...,0.000646,0.000102,0.000170,0.000177,0.000067,0.000349,0.000591,0.000073,0.000192,0.000232
2,B3EWF8,0.000552,0.000389,0.000302,0.001179,0.000920,0.000544,0.000348,0.004233,0.000743,...,0.001414,0.000364,0.000428,0.000570,0.000220,0.001233,0.001543,0.000244,0.000556,0.000651
3,C0HJD3,0.000761,0.000516,0.000408,0.001501,0.001120,0.000692,0.000463,0.005127,0.000977,...,0.001586,0.000504,0.000521,0.000763,0.000308,0.001731,0.001928,0.000344,0.000711,0.000815
4,P01391,0.000803,0.000527,0.000452,0.001606,0.001167,0.000688,0.000496,0.005637,0.001050,...,0.001658,0.000521,0.000528,0.000768,0.000300,0.001742,0.001916,0.000342,0.000721,0.000844